CREATE TABLE IF NOT EXISTS employments
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    employment_status character varying,
    employer character varying,
    salary numeric,
    "position" character varying,
    work_experience_total integer,
    work_experience_current integer,
    CONSTRAINT employments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS passports
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    series character varying,
    "number" character varying,
    issue_date date,
    issue_branch character varying,
    CONSTRAINT passports_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS loan_offers
(
    application_id bigint NOT NULL,
    requested_amount numeric,
    total_amount numeric,
    term integer,
    monthly_payment numeric,
    rate numeric,
    is_insurance_enabled boolean,
    is_salary_client boolean,
    CONSTRAINT loan_offers_pkey PRIMARY KEY (application_id)
);

CREATE TABLE IF NOT EXISTS clients
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    last_name character varying,
    first_name character varying,
    middle_name character varying,
    email character varying,
    gender character varying,
    marital_status character varying,
    dependent_amount integer,
    passport_id bigint,
    employment_id bigint,
    account character varying,
    birth_date date,
    CONSTRAINT clients_pkey PRIMARY KEY (id),
    CONSTRAINT employment_id FOREIGN KEY (employment_id)
        REFERENCES employments (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT passport_id FOREIGN KEY (passport_id)
        REFERENCES passports (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
);

CREATE TABLE IF NOT EXISTS credits
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    amount numeric,
    term integer,
    monthly_payment numeric,
    rate numeric,
    psk numeric,
    is_insurance_enabled boolean,
    is_salary_client boolean,
    credit_status character varying,
    CONSTRAINT credits_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS applications
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    status character varying,
    creation_date date,
    applied_offer_id bigint,
    sign_date date,
    ses_code character varying,
    client_id bigint,
    credit_id bigint,
    CONSTRAINT applications_id_pkey PRIMARY KEY (id),
    CONSTRAINT applied_offer_id_fkey FOREIGN KEY (applied_offer_id)
        REFERENCES loan_offers (application_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT client_id_fkey FOREIGN KEY (client_id)
        REFERENCES clients (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT credit_id_fkey FOREIGN KEY (credit_id)
        REFERENCES credits (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
);

CREATE TABLE IF NOT EXISTS applications_status_history
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    application_id bigint NOT NULL,
    status character varying,
    "time" timestamp without time zone,
    change_type character varying,
    CONSTRAINT applications_status_history_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS payments
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "number" integer,
    date date,
    total_payment numeric,
    interest_payment numeric,
    debt_payment numeric,
    remaining_debt numeric,
    credit_id bigint,
    CONSTRAINT payments_id_pkey PRIMARY KEY (id),
    CONSTRAINT credit_id_fkey FOREIGN KEY (credit_id)
        REFERENCES credits (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
);