package qiwi.application.enums;

public enum Status {
    PREAPPROVAL, CLIENT_DENIED, APPROVED,
    CC_DENIED, CC_APPROVED,
    PREPARE_DOCUMENTS, DOCUMENTS_CREATED, DOCUMENTS_SIGNED,
    CREDIT_ISSUED
}
